Contribute: Various fixes from TV 2
nrkno/tv-automation-server-core pull request #326
Opened 2020-09-15 14:04 UTC by thomasslee97

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A variety of fixed are included in this PR:
- Copy adLibSourceId to continuation pieces for an infinite
  - Fixes a bug where continuation pieces of an infinite would not have the adLibSourceId copied to them, which is required for "toggling" and infinite in dashboards.
- chore: use cache for expected playout items for adLibs
  - Previously this would make a direct database call, rather than the cache. This has no performance benefit right now, but is more consistent and may mean that a performance improvement is seen in the future with continued work on the caching system.
- fix: Standalone shelf route
  - The routing for standalone shelf views had been lost at some point, this restores the missing route.
- fix: arrow overlapping with extra time label
  - Small visual fix to the positioning of the overflow time label.
- fix: Crop WithinPart piece instances
  - There was a difference between what the UI was expecting (a unix timestamp) and what the data in the database contained (time relative to the start of the part). This resulted in pieces with WithinPart lifespans not getting cropped correctly when stopped (e.g. by stopping pieces on a sourcelayer).
- Set definitely ended to 1 second
  - With some experimentation at TV 2, we have found that the current definitely ended time (10 seconds) lets pieces live for too long, impacting performance. We have been testing with this value since 02/09 and have not found any issues created by lowering this value.
- fix: Don't push group name to used hotkeys
  - The hotkey group name was being pushed to usedHotkeys in dashboard panels, for every hotkey.
- fix: Dashboard crash
  - It's possible for props.layer to be undefined, so this PR changes it to be optional to enforce checking for the presence of layer.
- fix: Subscribe to all parts, pieces, and instances if in standalone shelf
  - fix: Only fetch piece instances for current, next, and previous part
  - Two commits. Previously, the standalone shelf wouldn't fetch any data, meaning it can't perform actions like stopping pieces and much of the context-aware functionality of the shelf was broken. These two commits mean that the standalone shelf will fetch data from the current, next, and previous parts; which has been enough data so far from testing.

**Status**

- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2020-09-18 08:55 UTC, nytamin commented
status: I'm going to ask @jstarpl and @Julusian to review this as well, when all 3 of us are happy we'll merge this in.

2020-09-18 11:28 UTC, Julusian approved these changes
For the bits I know anything about, I am happy.
Not 100% sure about DEFINITELY_ENDED_FUTURE_DURATION being 1 second, rather than a few seconds, but I am happy for that to be a testing note and we can increase it if it is a problem. The 10s was an arbitrary 'safe' number after all

2020-09-22 07:47 UTC, nytamin approved these changes

2020-09-23 06:34 UTC, jstarpl approved these changes
Erroneously marked this as approved. I think it would be best to keep the solution in place in R25 in SourceLayerItem.tsx:325 and I think the lines around RundownView.tsx:1575 need to be checked if they actually work.

2020-09-23 06:36 UTC, jstarpl requested changes
I realized that my previous comments have not been addressed.

2020-09-23 12:50 UTC, thomasslee97 commented on meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
> +					? innerPiece.stoppedPlayback - innerPiece.startedPlayback
It looks like this block of code was removed from r24 at least, so this fix is probably not relevant https://github.com/nrkno/tv-automation-server-core/commit/3001a044271ae10141bb68d854ea5ef0296276bf

2020-09-23 12:50 UTC, thomasslee97 commented on meteor/client/ui/RundownView.tsx
> +									playlist.currentPartInstanceId,
I have moved it to its own autorun here https://github.com/olzzon/tv-automation-server-core/commit/4ccdcb58df42bfdf4e9dbafd08f0ac15168a8be1

2020-09-23 12:52 UTC, thomasslee97 commented on meteor/client/ui/RundownView.tsx
> +									playlist.currentPartInstanceId,
And reduced data fetched, seeing as we don't need to fetch the rundown Ids given that the part instance Ids should be unique https://github.com/olzzon/tv-automation-server-core/commit/d474f5ebe9ccf4d9aa675c084b0f508eee97b70e

2020-09-23 12:54 UTC, thomasslee97 commented on meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
> +					? innerPiece.stoppedPlayback - innerPiece.startedPlayback
I've dropped the commit that produced this code in this PR

2020-09-23 22:12 UTC, jstarpl commented on meteor/client/ui/SegmentTimeline/SourceLayerItem.tsx
> +					? innerPiece.stoppedPlayback - innerPiece.startedPlayback
OK, I'm closing this then 👍

2020-09-23 22:13 UTC, jstarpl commented on meteor/client/ui/RundownView.tsx
> +									playlist.currentPartInstanceId,
Great 👍

2020-09-23 22:13 UTC, jstarpl approved these changes
Looks good!

2020-09-29 08:57 UTC, merged