Gui Optimizations
nrkno/tv-automation-server-core pull request #327
Opened 2020-09-15 15:18 UTC by thomasslee97

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

**Status**

- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2020-09-15 15:18 UTC, thomasslee97 commented
Needs input from @jstarpl @ianshade

2020-09-15 16:35 UTC, jstarpl requested changes
I think there are some clashes with some other improvements done over at NRK. These optimizations should coexist with each other, so all that's necessary is to make sure to keep the original ones where they are.

2020-09-15 16:35 UTC, jstarpl commented on meteor/client/ui/RundownView/RundownTiming.tsx
> +				this.onRefreshTimer()
```this.temporaryPartInstances = {}```
Should not be removed. The temporaryPartInstances is another speed-up/improvement that has been implemented at NRK and should be kept.

2020-09-17 10:12 UTC, jstarpl commented on meteor/client/ui/RundownView/RundownTiming.tsx
> +				this.onRefreshTimer()
Both lines are now included.

2020-09-17 10:12 UTC, jstarpl commented on meteor/client/lib/viewPort.ts
> +export const HEADER_MARGIN = 15 // NRK uses: 25
I restored the 25 setting.

2020-09-23 05:50 UTC, jstarpl approved these changes
Look good

2020-09-23 05:50 UTC, merged