Feat/mono repo
nrkno/tv-automation-server-core pull request #337
Opened 2020-09-25 15:49 UTC by Julusian

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This pulls in the various integration libraries to make this a mono repo.

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

**Status**

- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2020-11-06 18:28 UTC, sparkpunkd requested changes
Overall, this is absolutely the way to go and a great way to version inter-dependent packages. Most cool. 

I decided to take a practical approach to this review and try and get things up-and-running. There were a few bumps in the road, so I have a few requests for changes.

### Startup

The Quick-start instructions from README.md do not seem to work. From `npm start` I get ...

```
> cd ../packages && yarn build

yarn run v1.22.5
$ yarn workspaces run build

> tv-automation-sofie-blueprints-integration
$ trash dist && yarn build:main
'trash' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
```

I think this is because `trash` is not a dev dependency in the meteor package.json, even though it is for blueprints-integration.

If I manually `cd ../packages`, then `yarn build`, then back to meteor folder and just `meteor` then I'm up and running. If I `meteor npm run dev`, I get the same error as above.
A couple of questions:

* Can we make sure that following the README.md instructions is OK with the mono-repo?
* Can this process be simulated by the CI tests so it does not come back and bite us?

### Shared API between core and integration

I note that core itself does not actually make a reference to ...server-core-integration. This could be an opportunity for some shared typings? For example, file `corePeripherals.ts` in server-core-integration states that it is a copy of `meteor/lib/api/peripheralDevice.ts` in core.

### Local linking

I did a local `yarn link` from the embedded server-core-integration into media manager ... all good 👍 

### Typedoc documentation

I know there was some discussions on typedoc and how this fits with a mono-repo approach. I see an attempt to address this in `../packages/package.json`. However, I could not work out what to run to get this going as there is no script? Running `yarn docs` inside ...server-core-integration and ...blueprint-integration fails.

2020-11-06 20:29 UTC, Julusian commented
Thanks, this is exactly what I was hoping for in a review here :)

### Startup

That is strange, I have tested that myself and it does start. Maybe some quirk of a different os? Ill do some digging.

### Shared API between core and integration

I am expecting that to become a follow up task. I know Johan had some concerns about the dependencies that using server-core-integration directly would pull into core (ddp client), so I have opted to not do anything on this for now.

### Local linking

Perfect

### Typedoc documentation

Yeah, there isnt an explicit script as I didn't think anyone would run it locally. There is a ci step to generate and publish this on the master branch. Running `yarn typedoc` inside the packages folder will produce the docs folder containing both libraries. I shall add a script in case it is wanted.

2020-11-09 15:05 UTC, sparkpunkd approved these changes

2020-11-09 17:34 UTC, sparkpunkd commented
Approved due to:
* issues with Quick Start was a local meteor install corruption, not this repo
* shared API between core and core-integration package can be a topic of further discussion
* the build of the documentation for the packages is now working and has a script

2020-11-16 18:55 UTC, merged