fix: Remove deleted segments from ingestDataCache
nrkno/tv-automation-server-core pull request #369
Opened 2020-10-27 13:53 UTC by thomasslee97

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Cleans up segments from `ingestDataCache` when `dataSegmentDelete` is recieved.

* **What is the current behavior?** (You can also link to an open issue here)
The cached ingest data for a segment remains after a segment is deleted from the NRCS.

* **What is the new behavior (if this is a feature change)?**
The ingest data will be cleaned up.

**Status**

- [X] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2020-10-27 15:01 UTC, Julusian approved these changes

2020-10-27 15:03 UTC, Julusian requested changes
Actually, I think the change would be better placed in handleRemovedSegment() in rundownInput.ts

MOS does this remove before this point, so we only need to change the flow for other gateways

2020-10-27 15:52 UTC, thomasslee97 commented
I'm not sure that is better, in `handleRemovedSegment` it would only make sense to do this operation around this line, and it feels like it would be conditional on this statement being true? https://github.com/nrkno/tv-automation-server-core/blob/9f350055865ffd27ebcc6ecda69860cf4bc605c8/meteor/server/api/ingest/rundownInput.ts#L1048
So it would make sense to bundle removing cached data in with removing the segment itself? Potentially it would be better to remove to `afterRemoveSegments`?

2020-11-16 17:30 UTC, Julusian approved these changes

2020-11-16 17:30 UTC, merged