Open shelf by default and shelf height settings
nrkno/tv-automation-server-core pull request #399
Opened 2020-12-01 13:21 UTC by thomasslee97

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This adds a setting to each rundown layout to set that the shelf should open by default when opening a rundown with that rundown layout. It also adds the ability to set a default shelf height, so if a height is not found in the local storage it will use that as the default, on a per layout basis. This setting can be left blank to fall back to the Sofie default. Finally, the shelf height is changed to be stored on a per-layout basis, as the comfortable viewing size for each layout may be different, so this allows users to switch between shelf layouts without the need to adjust the size every time they switch.

* **What is the current behavior?** (You can also link to an open issue here)
- Shelf is always hidden by default.
- Default shelf size is 50vh.
- Shelf size is stored "globally", meaning switching between layouts may require resizing the shelf to get a good fit for the shelf content.

* **What is the new behavior (if this is a feature change)?**
- Shelf can be set to open automatically when a particular rundown layout is in use (default is hidden).
- Default shelf size can be set on a per-layout basis (0 - 100, where 100 in the setting is full height (0vh)). This setting value is clamped to a max value (currently 95) as this prevents the user from being in a situation where they can't resize the shelf.
- Shelf size is stored on a per-layout basis using the layout `_id`.

* **Other information**:
Two new settings illustrated (Show Bucket setting is not part of this PR - screenshot taken from TV 2 core)
![image](https://user-images.githubusercontent.com/10697525/100745991-02ed7100-33d8-11eb-84ed-6aaecefa11d2.png)

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [X] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2020-12-01 13:23 UTC, thomasslee97 commented
Created as draft until tested at TV 2 on their staging environment.

2020-12-10 11:03 UTC, jstarpl requested changes
Seems alright, but I have a question on the purpose of `shelfResizedByUser` in the RundownView state. It's not clear to me what that value is used for, since the interactions between `isInspectorShelfExpanded`, `shelfResizedByUsers` and `rundownLayout.openByDefault` seem to indicate to me that it's redundant.

2020-12-10 11:36 UTC, thomasslee97 commented on meteor/client/ui/RundownView.tsx
> +											(!this.state.shelfResizedByUser && this.state.rundownLayout?.openByDefault)
If the selected layout changes or the layout data arrives late, it prevents the shelf from popping into view if the user has already chosen to hide it

2020-12-10 12:14 UTC, jstarpl commented on meteor/client/ui/RundownView.tsx
> +											(!this.state.shelfResizedByUser && this.state.rundownLayout?.openByDefault)
OK, now I get it. Could you perhaps add some code documentation on the State interface to clarify the purpose and perhaps change the name of the flag to `wasShelfResizedByUser` to indicate that this describes a past event and not a continuous action?

2020-12-10 12:18 UTC, thomasslee97 commented on meteor/client/ui/RundownView.tsx
> +											(!this.state.shelfResizedByUser && this.state.rundownLayout?.openByDefault)
I've made those changes

2020-12-10 12:51 UTC, jstarpl approved these changes

2020-12-10 12:52 UTC, merged