chore: add readme section about version numbering
nrkno/tv-automation-server-core pull request #458
Opened 2021-02-12 19:27 UTC by Julusian

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

docs update

* **Other information**:

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2021-02-13 09:21 UTC, nytamin approved these changes

2021-02-15 10:20 UTC, gundelsby requested changes

2021-02-15 10:20 UTC, gundelsby commented on README.md
> +This project does not follow semver. We believe that semver does not make sense for this system as there are so many moving parts that a majority releases could be considered breaking in some way.
_a majority_ **of** _releases_

2021-02-15 11:41 UTC, Julusian commented on README.md
> +This project does not follow semver. We believe that semver does not make sense for this system as there are so many moving parts that a majority releases could be considered breaking in some way.
good spot :)

2021-02-15 11:42 UTC, merged