Added button overview, and adjusted the R joystick
nrkno/tv-automation-server-core pull request #471
Opened 2021-03-02 09:43 UTC by tsorbo

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Listing of button id's for L, R, and L+R mode for JoyCon.
Adjusted the R JoyCon to take into account that it is less sensitive than the L JoyCon.

* **What is the current behavior?** (You can also link to an open issue here)
The R JoyCon never reaches full speed ahead / reverse, which L JoyCon does.

* **What is the new behavior (if this is a feature change)?**
L and R are now more equal in response / sensitivity for the joystick.

* **Other information**:

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [ ] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2021-03-02 10:27 UTC, jesperstarkar approved these changes

2021-03-05 08:20 UTC, sparkpunkd requested changes
Not passing type check. Error is:

```
> tsc --noEmit -p tsconfig.json

client/ui/Prompter/controller/shuttle-keyboard-device.ts(28,38): error TS2339: Property 'speedMap' does not exist on type 'PrompterConfig'.
```

2021-03-05 11:03 UTC, sparkpunkd reviewed
Building now. A couple of dependency validation checks are causing issues, but I'll fix those back on the main branch when releasing.

2021-03-05 11:03 UTC, sparkpunkd approved these changes
Approved.

2021-03-05 11:04 UTC, merged