Feat: next tally settings
nrkno/tv-automation-server-core pull request #487
Opened 2021-03-31 14:25 UTC by ianshade

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature with a change of default behavior.

* **What is the current behavior?** (You can also link to an open issue here)
In DashboardPanel, when establishing if an AdLib is next, in addition to next pieces' tags and ids, tags from unfinished pieces were checked. That (depending on CSS styling) might lead to displaying unfinished pieces as both on-air and next. This can be considered incorrect in most cases, except some specific use cases.

* **What is the new behavior (if this is a feature change)?**
By default, unfinished piece tags will not be taken into account when establishing if a piece is next.
Two options to are added to the Filter DashboardPanel.
  - _Current part can contain next pieces_ - this enables taking unfinished piece tags into account when establishing if a piece is next. It's up to the blueprints and/or the custom CSS to make sure the tally indication is correct.
  - _Indicate only one next piece per source layer_ - if enabled, only the first piece per each sourceLayer will be indicated as next, Piece ids and tags from the next part have priority over unfinished piece tags.

* **Other information**:
Screenshot
![image](https://user-images.githubusercontent.com/9103996/113156546-611d4a00-923a-11eb-8258-4195038916f2.png)

**Status**

- [ ] Code documentation for the relevant parts in the code have been added/updated by the PR author
- [x] The functionality has been tested by the PR author
- [ ] The functionality has been tested by NRK

2021-04-27 14:01 UTC, Julusian requested changes
Seems reasonable to me
A few bits to tidy, including a git submodule that appears to have been accidentally added

2021-05-21 09:07 UTC, ianshade commented on meteor/client/ui/Settings/RundownLayoutEditor.tsx
> +							<div className="mod mvs mhs">
Removed, it came from a different feature

2021-05-21 09:08 UTC, ianshade commented on meteor/client/ui/Shelf/DashboardPanel.tsx
> +			nextAdLibIds.includes(adLib._id) ||
Done

2021-05-21 09:08 UTC, ianshade commented on meteor/client/ui/Shelf/DashboardPanel.tsx
> +				if (oneNextPerSourceLayer) {
Done

2021-05-24 09:16 UTC, Julusian approved these changes

2021-06-04 13:15 UTC, merged